<?php 
require_once('modulos/01basico.html');
require_once('modulos/02tipos.html'); 
require_once('modulos/03variaveis.html'); 
require_once('modulos/04estruturasDeControle.html'); 
require_once('modulos/05array.html'); 
require_once('modulos/06repeticoes.html'); 
require_once('modulos/07funcoes.html'); 
require_once('modulos/08oo.html'); 
require_once('modulos/09includes.html'); 
require_once('modulos/10namespace.html'); 
require_once('modulos/11erros.html'); 
require_once('modulos/12sessaoCookies.html'); 
require_once('modulos/13api.html'); 
require_once('modulos/14formulario.html'); 
require_once('modulos/15BD.html'); 
?>